#ifndef _I2C_STATUS_H_
#define _I2C_STATUS_H_

#define ERR_INIT_I2C_FAILURE		ERR_BASE_I2C(-1)
#define ERR_BUS_NOT_FOUND			ERR_BASE_I2C(-2)
#define ERR_ADDR_NOT_FOUND			ERR_BASE_I2C(-3)
#define ERR_DATA_ADDR_NOT_FOUND		ERR_BASE_I2C(-4)
#define ERR_OPEN_I2C_DEV_FAILURE	ERR_BASE_I2C(-5)
#define ERR_WRITE_I2C_FAILURE		ERR_BASE_I2C(-6)
#define ERR_READ_I2C_FAILURE		ERR_BASE_I2C(-7)



#endif