#ifndef _UART_STATUS_H_
#define _UART_STATUS_H_

#define ERR_OP_EXPORT_FAILURE		ERR_BASE_GPIO(-1)
#define ERR_WR_EXPORT_FAILURE		ERR_BASE_GPIO(-2)
#define ERR_OP_UNEXPORT_FAILURE		ERR_BASE_GPIO(-3)
#define ERR_WR_UNEXPORT_FAILURE		ERR_BASE_GPIO(-4)
#define ERR_OP_DIRECTION_FAILURE	ERR_BASE_GPIO(-5)
#define ERR_WR_DIRECTION_FAILURE	ERR_BASE_GPIO(-6)
#define ERR_RD_DIRECTION_FAILURE	ERR_BASE_GPIO(-7)
#define ERR_OP_VALUE_FAILURE		ERR_BASE_GPIO(-8)
#define ERR_WR_VALUE_FAILURE		ERR_BASE_GPIO(-9)
#define ERR_RD_VALUE_FAILURE		ERR_BASE_GPIO(-10)


#endif